
CREATE TABLE schools (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    address TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, principal_name TEXT, phone TEXT, email TEXT, npsn TEXT, accreditation TEXT, website TEXT, logo_url TEXT);
CREATE TABLE classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    level TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    code TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER REFERENCES schools(id) ON DELETE CASCADE,
    class_id INTEGER REFERENCES classes(id) ON DELETE SET NULL,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('superadmin', 'admin', 'guru', 'pengawas', 'siswa', 'panitia')),
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, place_of_birth TEXT, date_of_birth TEXT, photo TEXT);
CREATE TABLE exam_types (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT DEFAULT '',
    start_time TEXT,
    end_time TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE exams (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    subject_id INTEGER REFERENCES subjects(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    duration_minutes INTEGER NOT NULL DEFAULT 60,
    start_time TEXT,
    end_time TEXT,
    is_active INTEGER NOT NULL DEFAULT 0,
    shuffle_questions INTEGER NOT NULL DEFAULT 0,
    show_result INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
, show_score_type TEXT DEFAULT 'after_submit', is_score_released INTEGER DEFAULT 0, exam_type_id INTEGER REFERENCES exam_types(id) ON DELETE SET NULL);
CREATE TABLE questions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type IN ('pilihan_ganda', 'pilihan_ganda_kompleks', 'isian_singkat', 'essay', 'benar_salah', 'menjodohkan')),
    question_text TEXT NOT NULL,
    question_number INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 1,
    media_type TEXT CHECK(media_type IN ('image', 'audio') OR media_type IS NULL),
    media_url TEXT,
    audio_max_plays INTEGER DEFAULT 3,
    options_json TEXT,
    correct_answer_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    school_id INTEGER NOT NULL REFERENCES schools(id) ON DELETE CASCADE,
    exam_id INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    token_code TEXT NOT NULL UNIQUE,
    is_released INTEGER NOT NULL DEFAULT 0,
    created_by INTEGER REFERENCES users(id),
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    expires_at TEXT NOT NULL
, released_at TEXT);
CREATE TABLE exam_participants (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id INTEGER NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
    student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(exam_id, student_id)
);
CREATE TABLE exam_teachers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	exam_id INTEGER NOT NULL,
	teacher_id INTEGER NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
	FOREIGN KEY (teacher_id) REFERENCES users(id) ON DELETE CASCADE,
	UNIQUE(exam_id, teacher_id)
);
CREATE TABLE exam_proctors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	exam_id INTEGER NOT NULL,
	proctor_id INTEGER NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
	FOREIGN KEY (proctor_id) REFERENCES users(id) ON DELETE CASCADE,
	UNIQUE(exam_id, proctor_id)
);
CREATE TABLE exam_type_participants (id INTEGER PRIMARY KEY AUTOINCREMENT, exam_type_id INTEGER NOT NULL REFERENCES exam_types(id) ON DELETE CASCADE, student_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(exam_type_id, student_id));
INSERT INTO "exam_type_participants" ("id","exam_type_id","student_id","created_at") VALUES(7,5,36,'2026-08-08 23:17:06');
CREATE TABLE student_attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL REFERENCES users(id),
    exam_id INTEGER NOT NULL REFERENCES exams(id),
    token_id INTEGER REFERENCES tokens(id),
    start_time TEXT NOT NULL DEFAULT (datetime('now')),
    end_time TEXT,
    submit_time TEXT,
    score REAL,
    total_points INTEGER,
    status TEXT NOT NULL DEFAULT 'mengerjakan' CHECK(status IN ('mengerjakan', 'selesai', 'waktu_habis')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
, violation_count INTEGER DEFAULT 0, violation_logs TEXT, objective_score REAL DEFAULT 0, is_paused INTEGER NOT NULL DEFAULT 0, paused_at TEXT);
CREATE TABLE student_answers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id INTEGER NOT NULL REFERENCES student_attempts(id) ON DELETE CASCADE,
    question_id INTEGER NOT NULL REFERENCES questions(id),
    answer_given TEXT,
    score_given REAL,
    is_correct INTEGER,
    is_doubted INTEGER NOT NULL DEFAULT 0,
    answered_at TEXT DEFAULT (datetime('now'))
);
CREATE TABLE uploaded_media (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    url TEXT NOT NULL UNIQUE,
    media_type TEXT NOT NULL CHECK(media_type IN ('image', 'audio')),
    uploaded_at TEXT NOT NULL DEFAULT (datetime('now'))
, uploaded_by INTEGER REFERENCES users(id), is_public INTEGER NOT NULL DEFAULT 0, name TEXT, school_id INTEGER REFERENCES schools(id));
INSERT INTO "schools" ("id","name","address","is_active","created_at","updated_at","principal_name","phone","email","npsn","accreditation","website","logo_url") VALUES(1,'MIS BUTUNG','Butung, Kel. Bontokamase',1,'2026-08-02 08:07:06','2026-08-04 10:15:11','MUHAMMAD JUFRI, S.Pd.I',NULL,NULL,NULL,'C',NULL,NULL);
INSERT INTO "schools" ("id","name","address","is_active","created_at","updated_at","principal_name","phone","email","npsn","accreditation","website","logo_url") VALUES(2,'MTS TANUNTUNG','Banyoro, Kel. Tanuntung',1,'2026-08-02 08:07:06','2026-08-09 01:36:29',NULL,NULL,NULL,NULL,'C',NULL,NULL);
INSERT INTO "classes" ("id","school_id","name","level","created_at","updated_at") VALUES(1,1,'X IPA 11','X','2026-08-02 08:07:06','2026-08-03 06:50:33');
INSERT INTO "classes" ("id","school_id","name","level","created_at","updated_at") VALUES(2,1,'XI IPS 2','XI','2026-08-02 08:07:06','2026-08-02 08:07:06');
INSERT INTO "classes" ("id","school_id","name","level","created_at","updated_at") VALUES(5,2,'VII',NULL,'2026-08-05 22:37:20','2026-08-05 22:37:20');
INSERT INTO "classes" ("id","school_id","name","level","created_at","updated_at") VALUES(6,2,'VIII',NULL,'2026-08-05 22:37:26','2026-08-05 22:37:26');
INSERT INTO "classes" ("id","school_id","name","level","created_at","updated_at") VALUES(7,2,'IX',NULL,'2026-08-05 22:37:30','2026-08-05 22:37:30');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(1,1,'Matematika','MTK','2026-08-02 08:07:06','2026-08-02 08:07:06');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(5,1,'Bahasa Indonesia','BIND','2026-08-04 10:16:10','2026-08-04 10:16:10');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(6,1,'Bahasa Inggris','BING','2026-08-04 10:16:25','2026-08-04 10:16:25');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(7,1,'Bahasa Arab','BAR','2026-08-04 10:16:42','2026-08-04 10:16:42');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(8,1,'Fikih','FIK','2026-08-04 10:16:52','2026-08-04 10:16:52');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(9,1,'Akidah Akhlak','AA','2026-08-04 10:17:01','2026-08-04 10:17:01');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(10,1,'Quran Hadis','QH','2026-08-04 10:17:15','2026-08-04 10:17:15');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(11,1,'Sejarah Kebudayaan Islam','SKI','2026-08-04 10:17:43','2026-08-04 10:17:43');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(12,1,'Penjaskes','PJOK','2026-08-04 10:17:51','2026-08-04 10:17:51');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(13,1,'Ilmu Pengetahuan Alam','IPA','2026-08-04 10:18:09','2026-08-04 10:18:09');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(14,1,'Ilmu Pengetahuan Sosial','IPS','2026-08-04 10:18:23','2026-08-04 10:18:23');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(15,2,'Matematika','MTK','2026-08-05 22:37:49','2026-08-05 22:37:49');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(16,2,'Ilmu Pengetahuan Sosial','IPS','2026-08-05 22:38:04','2026-08-05 22:38:04');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(17,2,'Ilmu Pengetahuan Alam','IPA','2026-08-05 22:38:27','2026-08-05 22:38:27');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(18,2,'Akidah Akhlak','AA','2026-08-05 22:38:35','2026-08-05 22:38:35');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(19,2,'Qur''an Hadis','QH','2026-08-05 22:38:49','2026-08-05 22:38:49');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(20,2,'Sejarah Kebudayaan Islam','SKI','2026-08-05 22:38:56','2026-08-05 22:38:56');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(21,2,'Fikih','FIK','2026-08-05 22:39:14','2026-08-05 22:39:14');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(22,2,'Pendidikan Pancasila','PKN','2026-08-05 22:39:24','2026-08-05 22:39:24');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(23,2,'Bahasa Inggris','BING','2026-08-05 22:39:39','2026-08-05 22:39:39');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(24,2,'Bahasa Indonesia','BIN','2026-08-05 22:39:47','2026-08-05 22:39:47');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(25,2,'Bahasa Arab','BAR','2026-08-05 22:39:57','2026-08-05 22:39:57');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(26,2,'Pendidikan Jasmani Olahraga dan Kesehatan','PJOK','2026-08-05 22:40:26','2026-08-05 22:40:26');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(27,2,'Seni Budaya','SB','2026-08-05 22:40:45','2026-08-05 22:40:45');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(28,2,'Prakarya','PRAK','2026-08-05 22:40:57','2026-08-05 22:40:57');
INSERT INTO "subjects" ("id","school_id","name","code","created_at","updated_at") VALUES(29,2,'Informatika','INF','2026-08-05 22:41:07','2026-08-05 22:41:07');
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(1,NULL,NULL,'superadmin','ab1f65147eb4a6d345ee408df300dd4b:6e74c1694d1c1d7429bc7c0f71e18b4015d11de42e553a0a1f8967d5990c0e31','Sistem Superadmin','superadmin',1,'2026-08-02 08:07:06','2026-08-02 08:07:06',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(18,2,NULL,'mtstanuntung','b224eb9192aa0c0b89a0e8bfff45538b:5c74a6fbd3d94d056b9124d21735c9981cccb72e3092df3ed86d1c6f1580564c','MTS TANUNTUNG','admin',1,'2026-08-04 02:29:16','2026-08-04 02:29:16',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(19,1,NULL,'misbutung','1ad4dd06dd98ff1c2ce67db3bcb27e9c:040d4088c4564f0243516d48cffa36d0208f533371d30a1bbab28af8b7f8b719','MIS BUTUNG','admin',1,'2026-08-04 02:30:33','2026-08-04 02:30:33',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(20,NULL,NULL,'syamsulbahri','31689d49c3de9cc34975c718f4ff4b33:db7a36c0cbe4be2fb9195bdc7497d5e56790c264368bad67e1ed984e7e7a1edd','SYAMSUL BAHRI','superadmin',1,'2026-08-04 02:44:50','2026-08-04 02:44:50',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(29,1,1,'1234567890','4936bd6ce9e272c84de4ace80653042c:2d57dfc65a8ad95ba5fba678f503126a7717416a5d23f35329f2de95d7daa3b6','Andi','siswa',1,'2026-08-04 10:41:50','2026-08-04 10:41:50','Bulukumba','2026-08-03',NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(30,1,NULL,'pengawas','a283c49a386972b92bd6a05c59670a7a:2049b3d49c991d0adefdd77cdb09cce2b5d27066c58fa3bc010bca61b9191c60','Syamsul Bahri','pengawas',1,'2026-08-04 10:52:03','2026-08-04 10:52:03',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(34,2,NULL,'syamsul','bb58aa7780187df2d15ac125c807e7ec:014243f77409d62c21f4e568a19f58869b316da3e089c90e184bc85c55b93a54','SYAMSUL BAHRI','guru',1,'2026-08-06 00:36:23','2026-08-06 00:36:23',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(35,2,NULL,'pengawas123','7fd8cd1f825095b087acfad3efe366d3:35597fc04b3a01a960998996df6bc539523184c20c322b627ac1819903522780','Pengawas Ruang','pengawas',1,'2026-08-06 00:37:58','2026-08-06 00:37:58',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(36,2,5,'1111111111','9366dd6b39a34879c44794649706e1d0:5520ee6bd45139cedbf60cce5781c0bb9538200ebfab1e4f6732b25f60dc803c','Siswa 1','siswa',1,'2026-08-06 00:42:13','2026-08-06 00:42:13',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(37,2,5,'2222222222','31e1c32b80655f661417e0c6b31b3261:d1546d87c5b3c7f4d65f904c4fb1598345f42c28fa7938dbb6b3cab8548ca634','Siswa 2','siswa',1,'2026-08-06 00:42:25','2026-08-06 00:42:25',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(38,2,NULL,'peng','1bed60c3435ed79d29667397f667851a:e93083de504715d871e3cbd65474978e6c012548f3cc05dc93bd8df29d8e72f3','Adqwnfkllnk','pengawas',1,'2026-08-06 23:06:57','2026-08-06 23:06:57',NULL,NULL,NULL);
INSERT INTO "users" ("id","school_id","class_id","username","password_hash","name","role","is_active","created_at","updated_at","place_of_birth","date_of_birth","photo") VALUES(39,2,NULL,'cat','e3784d8cb1ad5e3ef6a980cac7088d58:6f7b4abf40d3fa8e949a64ff8ff9d823c637d688477cda96d1568c082d8e3ff0','cafg','guru',1,'2026-08-06 23:07:44','2026-08-06 23:07:44',NULL,NULL,NULL);
INSERT INTO "exam_types" ("id","school_id","code","name","description","start_time","end_time","is_active","created_at") VALUES(1,1,'UMUM','Ujian Umum','Tipe ujian default untuk sistem','2026-08-05 00:00:43','2027-08-05 00:00:43',1,'2026-08-05 00:00:43');
INSERT INTO "exam_types" ("id","school_id","code","name","description","start_time","end_time","is_active","created_at") VALUES(5,2,'PAT26','Penilaian Akhir Tahun 2026','','2026-08-05T09:27','2026-08-24T07:17',1,'2026-08-05 23:17:58');
INSERT INTO "exams" ("id","school_id","subject_id","title","description","duration_minutes","start_time","end_time","is_active","shuffle_questions","show_result","created_by","created_at","updated_at","show_score_type","is_score_released","exam_type_id") VALUES(5,1,1,'PAS - Matematika 2026','',120,'2026-08-04T07:30','2026-08-04T09:28',1,1,0,NULL,'2026-08-03 06:51:38','2026-08-03 23:28:20','after_end_time',0,1);
INSERT INTO "exams" ("id","school_id","subject_id","title","description","duration_minutes","start_time","end_time","is_active","shuffle_questions","show_result","created_by","created_at","updated_at","show_score_type","is_score_released","exam_type_id") VALUES(13,2,16,'PAT26 - Ilmu Pengetahuan Sosial','',60,'2026-08-09T08:51','2026-08-24T07:17',0,1,0,18,'2026-08-09 00:51:28','2026-08-09 00:51:28','after_type_end_time',0,5);
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(254,13,'pilihan_ganda','<ol><li>Al Qur`an adalah Kalam Allah yang diturunkan kepada Nabi Muhammad saw, tertulis dalam mushaf&nbsp; berbahasa Arab, yang disampaikan kepada kita dengan jalan&nbsp;mutawatir,&nbsp;dan membacanya mengandung nilai ibadah, dimulai dengan surah&nbsp;al Fatihah &nbsp;dan diakhiri dengan surah&nbsp;An Nas.</li></ol><p>Sebagaimana telah dimaklumi, bahwa Al Qur`an disamping sebagai kitab sucinya ummat Islam juga merupakan sumber hukum Islam yang pertama dan utama. Sebagai kitab suci, Al Qur`an harus diimani dan diaplikasikan dalam kehidupan sehari-hari, baik sebagai pribadi, sebagai anggota keluarga dalam sebuah rumah tangga maupun sebagai warga masyarakat, bangsa dan negara Republik Indonesia tercinta.</p><p>Dua pernyataan yang sesuai dengan kedudukan Al-Qur’an adalah….</p>',1,1,NULL,NULL,3,'["Al qur’an kalam allah Swt.","Sumber hukum pertama dan utama","Al qur’an di jadikan azimat","Mempelajari al qur’an dan mencari kelemahannya"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(255,13,'pilihan_ganda','<p>      </p><ol><li><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237080/ujian-madrasah/media/njjncmrnqhgh3xmfdwv2.png"></li></ol><p>Berdasarkan ayat diatas sikap yang sesuai dengan kandungan ayat tersebut adalah….</p>',2,1,NULL,NULL,3,'["kemapanan hidup","kekayaan yang takterduga","kecintaan yang mendalam kepada allah","pikiran yang bebas"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(256,13,'pilihan_ganda','<ol><li>Rahmat Allah Swt adalah kebaikan-kebaikan darinya sifat rahmat Allah pada hadis dibawah ini adalah….</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237081/ujian-madrasah/media/xpojqmrypnfulgc86cp1.png"></p>',3,1,NULL,NULL,3,'["Rahmat allah ditunjukkan kepada manusia","Rahmat allah hanya untuk perorangan","Rahmat allah unuk orang yang beriman","Rahmat allah mendahului murkanya"]','"D"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(257,13,'pilihan_ganda','<div>Kandungan yang tepat pada qur’an surah al lail ayat 5,6 dan 7 pada pernyataan di bawah ini adalah</div>',4,1,NULL,NULL,3,'["Allah SWT bersumpah dengan menyebutkan gelapnya malam,terangnya siang,serta terciptanya laki-laki dan perempuan","Allah akan memberikan kemudahan bagi orang yang bertaqwa dan mau menginfakkan hartanya di jalannya.","Allah akan mengampuni semua hambanya,asalkan hamba tersebut bertaubat dengan taubatan nasuha","Allah akan menguji hambanya sesuai kemampuannya"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(258,13,'pilihan_ganda','<ol><li>Perhatikan hadis dibawah ini!</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237082/ujian-madrasah/media/areaofwz7uzulda4p3m8.png"></p><p>Akibat sifat kikir yang sesuai dengan kandungan hadis diatas adalah!</p>',5,1,NULL,NULL,3,'["Saling toleransi antar sesama teman ","Saling memfitnah dan menjelek-jelekkan sesama","Pertumpahan darah dan menghalalkan segala sesuatu yang diharamkan","Dimurkai Allah dan di asingkan oleh teman"]','"D"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(259,13,'pilihan_ganda','<div>Ghina membaca al qur’an pada bacaan <img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237083/ujian-madrasah/media/cxhd8rkcpc386sgzpij8.png"> di baca panjang 3 alif,pada lafadz tersebut termasuk bacaan ….</div>',6,1,NULL,NULL,3,'["Mad jaiz munfasil","Mad wajib muttasil","Mad thabi’i","Mad iwad"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(260,13,'pilihan_ganda','<ol><li>Perhaikan tabel dibawah ini!</li></ol><table><tbody><tr><td><p>A</p></td><td><p>B</p></td><td><p>C</p></td><td><p>D</p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237083/ujian-madrasah/media/ksblfyyi8qlthuqengur.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237084/ujian-madrasah/media/nr49qpn0puhxt6q4wclh.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237085/ujian-madrasah/media/hcfnxonvnb7lpu42hvhr.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237086/ujian-madrasah/media/ewjnnip8vulvx98ewm3r.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237086/ujian-madrasah/media/qygt2n3ct2oob9thfchv.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237087/ujian-madrasah/media/ge0cxfqflqmfxxzhkcjw.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237088/ujian-madrasah/media/lox9g2k8ay9iubb4h1mn.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237088/ujian-madrasah/media/nxev6tzyxbvtmbpxksog.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237089/ujian-madrasah/media/i3pgumirxskqxegbpcst.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237090/ujian-madrasah/media/ov8ebcvloe5itzmnpdsy.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237091/ujian-madrasah/media/eakcg3z3a8orrfvubkcl.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237091/ujian-madrasah/media/ranyb7myx6yoicxfda0p.png"></p></td></tr></tbody></table><p>Mengidentifikasi Lafadz yang termasuk hukum bacaan mad thabi’I dan mad wajib muttasil serta mad jaiz munfasil pada tabel diatas adalah.</p>',7,1,NULL,NULL,3,'["A dan B","B dan C","C dan D","D dan A"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(261,13,'pilihan_ganda','<ol><li>Ali anak yang nakal karena faktor lingkungan dan teman-temannya, tetapi dia mempunyai keinginan untuk bertaubat agar menjadi orang yang baik, Dia memunyai mutivasi untuk selalu bersikap optimis terhadap ampunan dan rahmat dari allah swt.</li></ol><p>Pada pernyataan diatas termasuk kandungan al qur’an surah….</p>',8,1,NULL,NULL,3,'["Az zumar ayat 51","Az zumar ayat 52","Az zumar ayat 53","Az zumar ayat 54"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(262,13,'pilihan_ganda','<div>Allah swt, memberikan ujian dan jalan keluar bagi semua hambanya sikap kaum mukminin ketika mendapat kemudahan dari allah swt, adalah….</div>',9,1,NULL,NULL,3,'["Bersikap biasa saja","Tidak menerima kemudahan tersebut","Memanfaatkan kemudahan tersebut","Bersukur kepada allah swt."]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(263,13,'pilihan_ganda','<ol><li>Perhatikan pernyataan dibawah ini!</li></ol><p>“Ketika kita menghendaki pertolongan dari allah swt. Maka kita harus bersikap sabar.jalan keluar yang dihadapi ada bersama kesulian-kesulitan tersebut”</p><p>Pada pernyataan diatas termasuk kandungan hadis riwayat…</p>',10,1,NULL,NULL,3,'["HR At tirmidzi","HR Annasa’I ","HR Muslim","HR Bilal"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(264,13,'pilihan_ganda','<ol><li>Perhatikan table berikut!</li></ol><table><tbody><tr><td><p>1</p></td><td><p>2</p></td><td><p>3</p></td><td><p>4</p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237092/ujian-madrasah/media/etz3ybm4hmezwljx22a5.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237093/ujian-madrasah/media/alczz6wasmg0m6irlfvy.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237093/ujian-madrasah/media/ovsezcdj2arnmnguna4e.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237094/ujian-madrasah/media/hagkbv7sbatuxxake39z.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237095/ujian-madrasah/media/cvoeoiadp6yynkwnoc6x.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237095/ujian-madrasah/media/qjpsea1j5chzpzmjk9jt.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237096/ujian-madrasah/media/zs1hoip3xwkzno6d5lef.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237097/ujian-madrasah/media/l7nrikhwhvfkwdqskx8b.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237098/ujian-madrasah/media/ld508r5z0ssyrdivalgi.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237099/ujian-madrasah/media/w0fr1jircqajtrbq39re.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237099/ujian-madrasah/media/c6fx0smqttcsa8d3xke4.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237100/ujian-madrasah/media/ohheqmunjcvr05nzzdsd.png"></p></td></tr></tbody></table><p>Lafadz bacaan mad iwad,mad arid lissukun serta mad layyin ditunjukkan pada kolom nomor….</p>',11,1,NULL,NULL,3,'["1 ,2, 3","1, 3, 2","1, 4, 2","1, 3, 4"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(265,13,'pilihan_ganda','<ol><li>Perhatikan ayat di bawah ini!</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237101/ujian-madrasah/media/fqrlvhjc8uzj9jtxqe7g.png"></p><p>Pada akhir ayat diatas hasan memanjangkan bacaannya, karena terdapat huruf wawu sukun yang didahului oleh huruf berharakat fathah dan setelahnya ada huruf hidup yang di wakafkan.hal tersebut dilakukan karena pada ayat terebut terdapat hokum bacaan  …</p>',12,1,NULL,NULL,3,'["Mad wajib muttasil","Mad layyin","Mad aridlissukun","Mad iwad"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(266,13,'pilihan_ganda','<div>Surah al baqarah ayat 254  menjelaskan perintah untuk menyedekahkan harta sesegera mungkin sebelum datangnya hari kiamat.pada ayat tersebut juga di jelaskan bahwa termasuk orang yang zalim,yaitu…</div>',13,1,NULL,NULL,3,'["Orang yang kikir","Orang yang durhaka","Orang kafir","Orang yang berdusta"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(267,13,'pilihan_ganda','<div>Surah al baqarah ayat 261  menjelaskan perumpamaan (nafkah yang dikeluarkan oleh) orang –orang yang menafkahkan hartanya dijalan Allah adalah serupa dengan sebutir benih yang menumbuhkan tujuh bulir, pada tiap-tiap bulir seratus biji. Allah melipat gandakan (ganjaran) bagi siapa yang dia kehendaki karena ...</div>',14,1,NULL,NULL,3,'["Mereka memperoleh pahala disisi Tuhan mereka","Tidak ada kekhawatiran terhadap mereka","Allah Maha luas (Karunia-Nya) lagi Maha mengetahui","Allah Maha kaya lagi Maha Penyantun"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(268,13,'pilihan_ganda','<ol><li>Perhatikan pernyataan dibawah ini!</li><li>Hakim anak yang dermawan, setiap hari dia menyisihkan uangnya untuk diberikan kepada teman kelasnya yang sudah tidak ada orang tuanya</li><li>Edo selalu meminta-minta kepada teman kelasnya karena uang jajannya selalu ditabung untuk kepeningan dirinya</li><li>Doni setiap hari meneraktir temannya makan, supaya temannya menyanjung dia.</li><li>Diki anak  yang demawan dia selalu memberi uang kepada tetangganya, tapi uang tersebut hasil mencuri.</li></ol><p>Dari pernyataan diatas manakah yang termasuk kandungan hadis riwayat bukhari dari hakim bin hizam.</p>',15,1,NULL,NULL,3,'["1","2","3","4"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(269,13,'pilihan_ganda','<ol><li>Hasan orang yang kaya dia berprofesi sebagai menejer perusahan.setiap hari dia memberi nafkah kepada keluarganya, dan dia tidak lupa juga memberi sodaqah kepada tetangganya yang tidak mampu.</li></ol><p>Pada penyataan diatas termasuk kandungan hadis…</p>',16,1,NULL,NULL,3,'["HR.An nasa’I ","HR. Muslim","HR. Bukhari","HR. At tirmidzi"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(270,13,'pilihan_ganda','<ol><li>Perhatikan tabel berikut ini!</li></ol><table><tbody><tr><td><p>1</p></td><td><p>2</p></td><td><p>3</p></td><td><p>4</p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237102/ujian-madrasah/media/b6cq5xmio7isbzxa4ojw.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237102/ujian-madrasah/media/rhrtlj6kye5esqccaslg.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237103/ujian-madrasah/media/xtvizfvnaj83xz4mptvf.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237104/ujian-madrasah/media/fozv9juxrctcsrrxspas.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237104/ujian-madrasah/media/rmdyavbvs81dwhnidwlu.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237105/ujian-madrasah/media/tiiajjxmrvxdahygoqlv.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237106/ujian-madrasah/media/h08vmjgiarusggv6ugeo.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237107/ujian-madrasah/media/o8x6kx2m0pzuyd4azjjj.png"></p></td></tr><tr><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237108/ujian-madrasah/media/gpcjpwook67tllqcsuse.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237108/ujian-madrasah/media/lxpdik73h4dr4vivghil.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237109/ujian-madrasah/media/asuokyrhgnp8armyxamy.png"></p></td><td><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237110/ujian-madrasah/media/dt6eos2aovvjrszluati.png"></p></td></tr></tbody></table><p>Pada tabel diatas manakah yang termasuk bacaan mad silah qasirah, mad tamkin, mad farqi</p>',17,1,NULL,NULL,3,'["1","2","3","4"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(271,13,'pilihan_ganda','<ol><li>Perhatikan tabel berikut!</li></ol><table><tbody><tr><td></td><td><p>1</p></td><td><p>2</p></td><td><p>3</p></td><td><p>4</p></td></tr><tr><td><p>Istilah</p></td><td><p>Silah</p></td><td><p>Badal</p></td><td><p>Tamkin</p></td><td><p>farqi</p></td></tr><tr><td><p>Arti</p></td><td><p>Pengganti</p></td><td><p>Hubungan</p></td><td><p>Penetapan</p></td><td><p>Pembeda</p></td></tr></tbody></table><p>Yang istilah arti tidak sesuai adalah…</p>',18,1,NULL,NULL,3,'["1 dan 2","2 dan 3","3 dan 4","1 dan 4"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(272,13,'pilihan_ganda','<ol><li>Perhatikan pernyataan berikut!</li></ol><p>  <img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237110/ujian-madrasah/media/rrhjheiuwcqfvqlfidt4.png"></p><ol><li>Riko membaca ayat  yang bergaris bawah di atas panjangnya 1 alif dua harokat                        </li><li>Amin membaca ayat  yang bergaris bawah di atas panjangnya dua harokat</li><li>Dimas membaca ayat  yang bergaris bawah di atas panjangnya 5 harokat</li><li>Karim membaca ayat  yang bergaris bawah di atas panjangnya 3 alif</li></ol><p>Diantara pernyataan-pernyataan di atas, yang benar tunjukkan pada nomor</p>',19,1,NULL,NULL,3,'["1 dan 2","3 dan 4","1 dan 3","2 dan 4"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(273,13,'pilihan_ganda','<ol><li>Sesuai kandungan qur’an surah Al A’la ayat 14-15,orang yang </li></ol><p>     beruntung dalah….</p>',20,1,NULL,NULL,3,'["Orang yang rajin bekerja","Orang beriman","Orang hemat","Orang yang menuntut ilmu"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(274,13,'pilihan_ganda','<ol><li><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237111/ujian-madrasah/media/zelqkfq3h8oul8mjdskn.png">Perhatikan ayat erikut ini!</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237112/ujian-madrasah/media/anz19sgmavqzspa1cv2p.png"> </p><p>Orang yang beruntung sesuai ayat diatas adalah…</p>',21,1,NULL,NULL,3,'["Beriman, senantiasa mengingat allah swt, dan mengerjakan salat","Beriman, mengamalkan prilaku yang baik","Beriman, jarang melaksanakan erinah allah swt.","Beriman, sering beramal dan berbohong"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(275,13,'pilihan_ganda','<ol><li>Perhatikan pernyataan dibawah ini!</li></ol><p>Manakah yang termasuk kandungan hadis riwayat muslim dari abu hurairah tentang hubungan kehidupan dunia dan akhirat.</p>',22,1,NULL,NULL,3,'["Manusia adalah mahluk yang lemah yang di tuntut untuk meminta dan bergantung hanya kepada allah swt, hanya allah tempat berkeluh kesah dari segala masalah. Hanya allah yang dapat memberikan solusi terhadap permasalahan tersebut.","Manusia adalah mahluk yang lemah yang dituntut untuk selalu meminta terhadap sesama mahluknya.karena manusia saling membutuhkan antara satu dengan yang lain","Manusia adalah mahluk yang sempurna dan saling membutuhkan antar sesama.","Manusia mahluk yang berakal ketika mempunyai permasalahan maka harus difikirkan sendiri tanpa meminta bantuan siapapun."]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(276,13,'pilihan_ganda','<ol><li>Perhatikan pengalan ayat berikut ini!</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237112/ujian-madrasah/media/oo6851sqwbtiqs5x3tnu.png"></p><p>Dari lafal di atas manakah contoh bacaan mad lazim musaqol kilmi</p>',23,1,NULL,NULL,3,'["1","2","3","4"]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(277,13,'pilihan_ganda','<ol><li>Perhatikan ayat di awah ini</li></ol><p><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237113/ujian-madrasah/media/d1zvvkytxgvhdumo9vlz.png"> </p><p>Hukum bacaan pada kata yang bergaris bawah adalah…</p>',24,1,NULL,NULL,3,'["mad lazim mukhoffaf kilmi","mad lazim musaqqol kilmi","mad badal","mad lazim harfi musaqqol"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(278,13,'pilihan_ganda','<div>Dian membaca al qur’an surah thaha ayat pertama ketika membaca lafal thaha di baca  panjang 1 alif dua harakat karena berada di awal surah termasuk hukum bacaan…</div>',25,1,NULL,NULL,3,'["Mad lazim mukhaffaf kilmi","Mad lazim musaqqal kilmi","Mad lazim mukhaffaf harfi","Mad lazim musaqqal harfi"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(279,13,'pilihan_ganda','<ol><li>Perhatikan ayat di bawah ini!</li></ol><p> <img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237114/ujian-madrasah/media/bqsbfkmiuz4lllg40tmu.png"> </p><p>kandungan yang tepat pada penggalan ayat diatas adalah…</p>',26,1,NULL,NULL,3,'["larangan memakan harta anak yatim secara batil","perintah berbuat adil pada sahabat","perintah menyempurnakan takaran dan timbangan","perintah agar berkata dengan jujur"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(280,13,'pilihan_ganda','<ol><li>Perhaikan pernyataan-pernyataan berikut ini!</li><li>Larangan mendekati harta anak yatim dengan batil</li><li>Perintah menyempurnakan takaran dan timbangan</li><li>Larangan mendekati riba yang membinasakan</li><li>Perintah menjadi orang yang amanah dalam bermuamalah  </li><li>Perintah beraku adil terhadap siapapun meskipun terhadap kerabat dekat</li></ol><p>Kandungan surah al an’am ayat 152 ditunjukkan pada…</p>',27,1,NULL,NULL,3,'["1, 2, 3","1, 3, 4","1, 2, 5","1, 3, 5"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(281,13,'pilihan_ganda','<ol><li>Perhatikan pernyataan berikut ini!</li><li>Tinggalkanlah sesuatu yang meragukan, kepada sesuatu yang tidak meragukan dan kita harus berbuat adil</li><li>Ketika kita mendapatkan musibah harus sabar dan salat karena olat adalah tiang agama</li><li>Kita harus jujur dalam muamalah tidak boleh mengurangi timbangan</li><li>Ketika kita mendapatkan satukesulitan pasti ada kemudahan</li></ol><p>Diantara pernyataan hadis diatas,manakah yang termasuk kandungan hadis yang diriwayatkan oleh imam at tirmidzi dari hasan bin ali</p>',28,1,NULL,NULL,3,'["A","B","C","D"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(282,13,'pilihan_ganda','<div>Jujur dalam bermuamalah dapat di artikan sebagai kesesuaian antara pikiran, ucapan dan tindakan dalam berinteraksi sosial dengan sesama manusia di kehidupan sehari-hari, andi setiap hari berprofesi sebagai pedagang beras tapi ketika ada orang yang membeli dia selalu mengurangi takarannya,diko mengetahui tindakan andi tersebut lalu diko menegurnya.andi tidak meresponnya karna dia ingin mendapatkan hasil yang lebih banyak.tindakan yang sesuia yang harus lakukan yang berpedoman pada hadis riwayat at tirmidzi dari hasan bin ali adalah </div>',29,1,NULL,NULL,3,'["Mengajak pedagang supaya tidak curang dalam menakar.","Tidak merepon ajakan diko","Kita harus mementingkan diri kita sendiri","Harus bersikap adil."]','"A"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(283,13,'pilihan_ganda','<ol><li>Perhatikan kolom dibawah ini!</li></ol><table><tbody><tr><td><p>NO</p></td><td><p>KALIMAT</p></td><td><p>BACAAN</p></td></tr><tr><td><p>1</p></td><td><p><strong><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237115/ujian-madrasah/media/d6f1mbaki45dofvlmxrn.png"></strong></p></td><td><p>Naql</p></td></tr><tr><td><p>2</p></td><td><p><strong><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237115/ujian-madrasah/media/dszodhyhpwwyslgui2jw.png"></strong></p></td><td><p>isymam</p></td></tr><tr><td><p>3</p></td><td><p><strong><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237116/ujian-madrasah/media/yj7deuihmpabisuuwvc0.png"></strong></p></td><td><p>Imalah</p></td></tr><tr><td><p>4</p></td><td><p><strong><img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237117/ujian-madrasah/media/pmsgfynpauykua7m7dkg.png"></strong></p></td><td><p>tashil</p></td></tr></tbody></table><p>Pasangan yang tepat pada kolom diatas adalah….</p>',30,1,NULL,NULL,3,'["1","2","3","4"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(284,13,'pilihan_ganda','<div>Kirana anak yang solihah dia rajin mengaji di masjid bersama temannya,ketika dia membaca al qur’an kepada gurunya kirana ditegor  tepat pada ayat <img src="https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237118/ujian-madrasah/media/t0odv8lad9vmjuyhcsvc.png"> kirana membaca dengan bacaan yang kurang sesuai dengan kaidah ilmu tajwid.bagaimana cara yang tepat membaca ayat tersebut….</div>',31,1,NULL,NULL,3,'["Dengan cara mencucung kedua bibir","Dengan merubah mahorijul hurufnya","Dengan cara membaca huruf berharakat fathah yang dimiringkan ke kasrah","Dengan cara memasukkukkan bacaan lalu di idghomkan"]','"C"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(285,13,'pilihan_ganda','<ol><li>“Mengkombinasikan harakat fathah dengan harakar dommah disertai </li></ol><p>      monyong bibirnya “termasuk definisi dari….</p>',32,1,NULL,NULL,3,'["Imalah","Isymam","Tashil","Naql"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(286,13,'pilihan_ganda','<div>Zidan sering kali pergi ke majlis ilmu, ketika diperjalanan dia bertemu dengan temannya yang bernama dika lalu dia mengajaknya untuk bergabung di majlis tersebut,sesampainya dimajlis zidan dan dika duduk dengan tenang dan mengindahkan aturan majlis sambil mendengarkan kajian dari salah satu mubaligh,zidan dan dika memunyai keinginan ingin diangkat derajatnya oleh allah swt, prilaku yang dilakukan oleh zidan tersebut tercermin dalam al qur’an</div>',33,1,NULL,NULL,3,'["QS. Al Mujadalah (58):10","QS. Al Mujadalah (58):11","QS. Al Mujadalah (58):12","QS. Al Mujadalah (58):13"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(287,13,'pilihan_ganda','<div>Di bawah ini manakah yang termasuk kandungan hadis riwayat ibnu majah dari shofwan assal al muradi…</div>',34,1,NULL,NULL,3,'["Allah akan mengangkat derajat bagi rang yang berilmu","Malaikat akan mengepakkan sayapnya karena ridha terhadap prilakunya","Allah akan memeri jalan keluar bagi orang yang sholeh","Malaikat akan membimbing orang yang berilmu"]','"B"','2026-08-09 00:58:38');
INSERT INTO "questions" ("id","exam_id","type","question_text","question_number","points","media_type","media_url","audio_max_plays","options_json","correct_answer_json","created_at") VALUES(288,13,'pilihan_ganda','<div>Dalam hadis riwayat muslim dari abuhurairah, allah swt menjanjikan sesuatu terhadap orang yang menimba ilmu yaitu…</div>',35,1,NULL,NULL,3,'["Dimudahkan jalannya menuju surga","Dimudahkan hidupnya didunia dan ahirat","Dimudahkan mencari rizqi","Dimudahkan menggapai kebahagiaan"]','"A"','2026-08-09 00:58:38');
INSERT INTO "exam_participants" ("id","exam_id","student_id","created_at") VALUES(30,13,36,'2026-08-09 00:51:28');
INSERT INTO "exam_participants" ("id","exam_id","student_id","created_at") VALUES(31,13,37,'2026-08-09 00:51:28');
INSERT INTO "exam_teachers" ("id","exam_id","teacher_id","created_at") VALUES(13,13,34,'2026-08-09 00:51:34');
INSERT INTO "exam_teachers" ("id","exam_id","teacher_id","created_at") VALUES(14,13,39,'2026-08-09 00:51:34');
INSERT INTO "exam_proctors" ("id","exam_id","proctor_id","created_at") VALUES(18,13,35,'2026-08-09 00:51:37');
INSERT INTO "exam_proctors" ("id","exam_id","proctor_id","created_at") VALUES(19,13,38,'2026-08-09 00:51:37');
INSERT INTO "exam_type_participants" ("id","exam_type_id","student_id","created_at") VALUES(8,5,37,'2026-08-08 23:17:06');
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(5,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1785749539/y898h4hoq9ujyxzv98za.png','image','2026-08-03 09:32:20',NULL,0,'qr',NULL);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(6,'https://res.cloudinary.com/dfhtjgwcz/video/upload/v1785750312/iv7gf9j2b8nukoxijdf8.mp3','audio','2026-08-03 09:45:13',NULL,0,NULL,NULL);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(218,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237080/ujian-madrasah/media/njjncmrnqhgh3xmfdwv2.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(219,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237081/ujian-madrasah/media/xpojqmrypnfulgc86cp1.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(220,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237082/ujian-madrasah/media/areaofwz7uzulda4p3m8.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(221,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237083/ujian-madrasah/media/cxhd8rkcpc386sgzpij8.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(222,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237083/ujian-madrasah/media/ksblfyyi8qlthuqengur.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(223,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237084/ujian-madrasah/media/nr49qpn0puhxt6q4wclh.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(224,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237085/ujian-madrasah/media/hcfnxonvnb7lpu42hvhr.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(225,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237086/ujian-madrasah/media/ewjnnip8vulvx98ewm3r.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(226,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237086/ujian-madrasah/media/qygt2n3ct2oob9thfchv.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(227,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237087/ujian-madrasah/media/ge0cxfqflqmfxxzhkcjw.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(228,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237088/ujian-madrasah/media/lox9g2k8ay9iubb4h1mn.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(229,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237088/ujian-madrasah/media/nxev6tzyxbvtmbpxksog.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(230,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237089/ujian-madrasah/media/i3pgumirxskqxegbpcst.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(231,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237090/ujian-madrasah/media/ov8ebcvloe5itzmnpdsy.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(232,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237091/ujian-madrasah/media/eakcg3z3a8orrfvubkcl.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(233,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237091/ujian-madrasah/media/ranyb7myx6yoicxfda0p.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(234,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237092/ujian-madrasah/media/etz3ybm4hmezwljx22a5.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(235,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237093/ujian-madrasah/media/alczz6wasmg0m6irlfvy.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(236,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237093/ujian-madrasah/media/ovsezcdj2arnmnguna4e.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(237,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237094/ujian-madrasah/media/hagkbv7sbatuxxake39z.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(238,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237095/ujian-madrasah/media/cvoeoiadp6yynkwnoc6x.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(239,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237095/ujian-madrasah/media/qjpsea1j5chzpzmjk9jt.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(240,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237096/ujian-madrasah/media/zs1hoip3xwkzno6d5lef.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(241,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237097/ujian-madrasah/media/l7nrikhwhvfkwdqskx8b.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(242,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237098/ujian-madrasah/media/ld508r5z0ssyrdivalgi.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(243,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237099/ujian-madrasah/media/w0fr1jircqajtrbq39re.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(244,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237099/ujian-madrasah/media/c6fx0smqttcsa8d3xke4.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(245,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237100/ujian-madrasah/media/ohheqmunjcvr05nzzdsd.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(246,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237101/ujian-madrasah/media/fqrlvhjc8uzj9jtxqe7g.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(247,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237102/ujian-madrasah/media/b6cq5xmio7isbzxa4ojw.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(248,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237102/ujian-madrasah/media/rhrtlj6kye5esqccaslg.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(249,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237103/ujian-madrasah/media/xtvizfvnaj83xz4mptvf.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(250,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237104/ujian-madrasah/media/fozv9juxrctcsrrxspas.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(251,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237104/ujian-madrasah/media/rmdyavbvs81dwhnidwlu.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(252,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237105/ujian-madrasah/media/tiiajjxmrvxdahygoqlv.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(253,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237106/ujian-madrasah/media/h08vmjgiarusggv6ugeo.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(254,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237107/ujian-madrasah/media/o8x6kx2m0pzuyd4azjjj.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(255,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237108/ujian-madrasah/media/gpcjpwook67tllqcsuse.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(256,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237108/ujian-madrasah/media/lxpdik73h4dr4vivghil.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(257,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237109/ujian-madrasah/media/asuokyrhgnp8armyxamy.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(258,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237110/ujian-madrasah/media/dt6eos2aovvjrszluati.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(259,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237110/ujian-madrasah/media/rrhjheiuwcqfvqlfidt4.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(260,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237111/ujian-madrasah/media/zelqkfq3h8oul8mjdskn.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(261,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237112/ujian-madrasah/media/anz19sgmavqzspa1cv2p.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(262,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237112/ujian-madrasah/media/oo6851sqwbtiqs5x3tnu.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(263,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237113/ujian-madrasah/media/d1zvvkytxgvhdumo9vlz.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(264,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237114/ujian-madrasah/media/bqsbfkmiuz4lllg40tmu.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(265,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237115/ujian-madrasah/media/d6f1mbaki45dofvlmxrn.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(266,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237115/ujian-madrasah/media/dszodhyhpwwyslgui2jw.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(267,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237116/ujian-madrasah/media/yj7deuihmpabisuuwvc0.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(268,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237117/ujian-madrasah/media/pmsgfynpauykua7m7dkg.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
INSERT INTO "uploaded_media" ("id","url","media_type","uploaded_at","uploaded_by","is_public","name","school_id") VALUES(269,'https://res.cloudinary.com/dfhtjgwcz/image/upload/v1786237118/ujian-madrasah/media/t0odv8lad9vmjuyhcsvc.png','image','2026-08-09 00:58:38',34,0,'Gambar Import Word',2);
﻿PRAGMA defer_foreign_keys=TRUE;
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('schools',2);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('classes',7);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('subjects',29);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('users',39);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exams',13);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('tokens',61);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exam_participants',31);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exam_proctors',19);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exam_teachers',14);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('student_attempts',43);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('uploaded_media',269);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exam_types',5);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('exam_type_participants',8);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('questions',288);
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('student_answers',1088);
CREATE INDEX idx_users_school ON users(school_id);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_exams_school ON exams(school_id);
CREATE INDEX idx_exams_active ON exams(is_active);
CREATE INDEX idx_tokens_exam ON tokens(exam_id);
CREATE INDEX idx_tokens_code ON tokens(token_code);
CREATE INDEX idx_attempts_student ON student_attempts(student_id);
CREATE INDEX idx_attempts_exam ON student_attempts(exam_id);
CREATE INDEX idx_attempts_status ON student_attempts(status);
CREATE INDEX idx_participants_exam ON exam_participants(exam_id);
CREATE INDEX idx_participants_student ON exam_participants(student_id);
CREATE INDEX idx_exam_participants_exam ON exam_participants(exam_id);
CREATE INDEX idx_exam_participants_student ON exam_participants(student_id);
CREATE INDEX idx_exam_teachers_exam ON exam_teachers(exam_id);
CREATE INDEX idx_exam_teachers_teacher ON exam_teachers(teacher_id);
CREATE INDEX idx_exam_proctors_exam ON exam_proctors(exam_id);
CREATE INDEX idx_exam_proctors_proctor ON exam_proctors(proctor_id);
CREATE INDEX idx_uploaded_media_url ON uploaded_media(url);
CREATE INDEX idx_exam_types_school ON exam_types(school_id);
CREATE INDEX idx_exam_types_active ON exam_types(is_active);
CREATE INDEX idx_etp_type ON exam_type_participants(exam_type_id);
CREATE INDEX idx_etp_student ON exam_type_participants(student_id);
CREATE INDEX idx_uploaded_media_school ON uploaded_media(school_id);
CREATE INDEX idx_exam_type_participants_type ON exam_type_participants(exam_type_id);
CREATE INDEX idx_exam_type_participants_student ON exam_type_participants(student_id);
CREATE INDEX idx_tokens_exam_school ON tokens(exam_id, school_id);
CREATE INDEX idx_questions_exam ON questions(exam_id);
CREATE INDEX idx_questions_type ON questions(type);
CREATE INDEX idx_attempts_exam_student ON student_attempts(exam_id, student_id);
CREATE INDEX idx_answers_attempt ON student_answers(attempt_id);
CREATE INDEX idx_answers_question ON student_answers(question_id);
CREATE INDEX idx_answers_attempt_question ON student_answers(attempt_id, question_id);
CREATE INDEX idx_uploaded_media_school_public ON uploaded_media(school_id, is_public);
